import Head from "next/head";
import Header from "../components/header/Header";
import Nav from "../components/Navbar/Nav";
import Result from "../components/result/Results";
import axios from "../axios";
import requests from "../utils/requests";
import Results from "../components/result/Results";

export default function Home({results}) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Navbar */}
      <Nav />
      {/* Result */}
      <Results
       results={results} />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;
  const request = await axios
    .get(requests[genre]?.url || requests.fetchTreding.url)
    .then((res) => res.data);

  return {
    props: {
      results: request.results,
    },
  };
};
